### ISSUE TITLE
Build failure on GHC 8

### ISSUE THREAD

**Issue by ocharles** [well-typed/generics-sop#20]
```
setupCompilerEnvironmentPhase
Build with /nix/store/fih8xk5p1yxjawyagm7ns3l3grjwmh41-ghc-8.1.20161109.
ghc-pkg: unable to decommit memory: Invalid argument
ghc-pkg: unable to decommit memory: Invalid argument
unpacking sources
unpacking source archive /nix/store/7qqjfh7xfv8y78cvj9qa7s0gk4gq6mqy-generics-sop-0.2.2.0.tar.gz
source root is generics-sop-0.2.2.0
setting SOURCE_DATE_EPOCH to timestamp 1468130830 of file generics-sop-0.2.2.0/test/Example.hs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-generics-sop-0.2.2.0.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-generics-sop-0.2.2.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-generics-sop-0.2.2.0.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/lib/ghc-8.1.20161109/generics-sop-0.2.2.0 --enable-split-objs --disable-library-profiling --disable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring generics-sop-0.2.2.0...
Dependency base >=4.6 && <5: using base-4.9.0.0
Dependency generics-sop -any: using generics-sop-0.2.2.0
Dependency ghc-prim >=0.3 && <0.6: using ghc-prim-0.5.0.0
Dependency template-haskell >=2.8 && <2.12: using template-haskell-2.11.0.0
Setup: unable to decommit memory: Invalid argument
Source component graph:
    component lib
    component test:generic-sop-examples dependency lib
Configured component graph:
    component generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x
        include base-4.9.0.0
        include ghc-prim-0.5.0.0
        include template-haskell-2.11.0.0
    component generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x-generic-sop-examples
        include base-4.9.0.0
        include generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x
Linked component graph:
    unit generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x
        include base-4.9.0.0
        include ghc-prim-0.5.0.0
        include template-haskell-2.11.0.0
    unit generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x-generic-sop-examples
        include base-4.9.0.0
        include generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x
Ready component graph:
    definite generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x
        depends base-4.9.0.0
        depends ghc-prim-0.5.0.0
        depends template-haskell-2.11.0.0
    definite generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x-generic-sop-examples
        depends base-4.9.0.0
        depends generics-sop-0.2.2.0-9w3u9oOObG6ENcL8IZfj8x
Using Cabal-1.25.0.0 compiled by ghc-8.1
Using compiler: ghc-8.1.20161109
Using install prefix:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0
Binaries installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/bin
Libraries installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/lib/ghc-8.1.20161109/generics-sop-0.2.2.0
Dynamic Libraries installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/lib/ghc-8.1.20161109/x86_64-linux-ghc-8.1.20161109
Private binaries installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/libexec
Data files installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/share/x86_64-linux-ghc-8.1.20161109/generics-sop-0.2.2.0
Documentation installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/share/doc/x86_64-linux-ghc-8.1.20161109/generics-sop-0.2.2.0
Configuration files installed in:
/nix/store/d7w3m1p8hbgxx35ydayiqvwsc23s3jz5-generics-sop-0.2.2.0/etc
No alex found
Using ar found on system at:
/nix/store/9kxhc2f3j5lcyh00zcrifvfly33n5m4r-binutils-2.27/bin/ar
No c2hs found
No cpphs found
Using gcc version 5.4.0 given by user at:
/nix/store/d78lwdgpd05c7qjdg4bvsx38jfy3vs43-gcc-wrapper-5.4.0/bin/gcc
Using ghc version 8.1.20161109 found on system at:
/nix/store/fih8xk5p1yxjawyagm7ns3l3grjwmh41-ghc-8.1.20161109/bin/ghc
Using ghc-pkg version 8.1.20161109 found on system at:
/nix/store/fih8xk5p1yxjawyagm7ns3l3grjwmh41-ghc-8.1.20161109/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.17.2 found on system at:
/nix/store/fih8xk5p1yxjawyagm7ns3l3grjwmh41-ghc-8.1.20161109/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/fih8xk5p1yxjawyagm7ns3l3grjwmh41-ghc-8.1.20161109/bin/hpc
Using hsc2hs version 0.68 found on system at:
/nix/store/fih8xk5p1yxjawyagm7ns3l3grjwmh41-ghc-8.1.20161109/bin/hsc2hs
Using hscolour version 1.24 found on system at:
/nix/store/1akjfhrqd0xandv1iyqs0sy4cgi5cvva-hscolour-1.24.1/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/d78lwdgpd05c7qjdg4bvsx38jfy3vs43-gcc-wrapper-5.4.0/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.27 found on system at:
/nix/store/9kxhc2f3j5lcyh00zcrifvfly33n5m4r-binutils-2.27/bin/strip
Using tar found on system at:
/nix/store/ipsnpg6csk11j07lzlsd7z5mm30wsb4x-gnutar-1.29/bin/tar
No uhc found
Setup: unable to decommit memory: Invalid argument
Setup: unable to decommit memory: Invalid argument
building
Preprocessing library generics-sop-0.2.2.0...
[ 1 of 13] Compiling Generics.SOP.BasicFunctors ( src/Generics/SOP/BasicFunctors.hs, dist/build/Generics/SOP/BasicFunctors.o )
[ 2 of 13] Compiling Generics.SOP.Sing ( src/Generics/SOP/Sing.hs, dist/build/Generics/SOP/Sing.o )
[ 3 of 13] Compiling Generics.SOP.Constraint ( src/Generics/SOP/Constraint.hs, dist/build/Generics/SOP/Constraint.o )
[ 4 of 13] Compiling Generics.SOP.Classes ( src/Generics/SOP/Classes.hs, dist/build/Generics/SOP/Classes.o )
[ 5 of 13] Compiling Generics.SOP.NP  ( src/Generics/SOP/NP.hs, dist/build/Generics/SOP/NP.o )
[ 6 of 13] Compiling Generics.SOP.NS  ( src/Generics/SOP/NS.hs, dist/build/Generics/SOP/NS.o )
[ 7 of 13] Compiling Generics.SOP.Metadata ( src/Generics/SOP/Metadata.hs, dist/build/Generics/SOP/Metadata.o )
[ 8 of 13] Compiling Generics.SOP.GGP ( src/Generics/SOP/GGP.hs, dist/build/Generics/SOP/GGP.o )
[ 9 of 13] Compiling Generics.SOP.Dict ( src/Generics/SOP/Dict.hs, dist/build/Generics/SOP/Dict.o )
[10 of 13] Compiling Generics.SOP.Universe ( src/Generics/SOP/Universe.hs, dist/build/Generics/SOP/Universe.o )
[11 of 13] Compiling Generics.SOP.TH  ( src/Generics/SOP/TH.hs, dist/build/Generics/SOP/TH.o )

src/Generics/SOP/TH.hs:230:25: error:
    • Ambiguous occurrence ‘Newtype’
      It could refer to either ‘Language.Haskell.TH.Syntax.Newtype’,
                               imported from ‘Language.Haskell.TH.Syntax’ at src/Generics/SOP/TH.hs:13:1-48
                            or ‘Generics.SOP.Metadata.Newtype’,
                               imported from ‘Generics.SOP.Metadata’ at src/Generics/SOP/TH.hs:16:1-28
                               (and originally defined at src/Generics/SOP/Metadata.hs:40:3-91)
    • In the Template Haskell quotation
        [| Newtype
             ($(stringE (nameModule' typeName)))
             ($(stringE (nameBase typeName)))
             ($(mdCon (head cs))) |]
```

**Comment by kosmikus** [comment]
Probably a recent TH change. It still works with ghc-8.0.1.20161018 and the same nominal version of TH. I'll try to get hold of a later snapshot.

**Comment by kosmikus** [comment]
Ok, I can reproduce this now. There seem to be more TH-related changes to be made than just the naming issue, so it needs CPP, but this is tricky since template-haskell still claims to be at 2.11 which is the same version also used in ghc-8.0.1 ...

**Comment by kosmikus** [comment]
@ocharles Anyway, this does not seem to be in 8.0.2, but only in master. I'm somewhat reluctant to re-release based on in-flux library changes in master. Do you need this to work?

**Comment by ocharles** [comment]
I do need it, as I'm trying to see if recent changes to GHC fix a bug in
reported on Track when compiling stuff at work. However, I understand the
concerns about cutting a release, and am happy to work off a branch (I can
fork and make the necessary changes, but wanted to raise the issue here
first)

**Comment by kosmikus** [comment]
@ocharles Ok, here you go: https://github.com/well-typed/generics-sop/tree/ghc-8.1

I've heard from Ben that there'll be a version bump for template-haskell soon, so then I could even move this to the generics-sop master branch.

**Comment by bgamari** [comment]
> I've heard from Ben that there'll be a version bump for template-haskell soon, ...
This has happened, by the way.

**Comment by kosmikus** [comment]
Ok, I've updated the branch accordingly. This means it'll now fail again with older 8.1 snapshots, but work correctly with the latest, and also still work with 8.0.2 and older. Will merge this to master soon.

**Comment by ocharles** [comment]
Sorry for the late reply, I was out on holiday just after opening the issue. The 8.1 branch works perfectly with the recent release candidate, thanks!

**Comment by kosmikus** [comment]
Merged to master. Closing.
