### ISSUE TITLE
Benchmarks fail to build on GHC 8.10.1

### ISSUE THREAD

**Issue by RyanGlScott** [well-typed/generics-sop#117]
If you attempt to compile `generics-sop-bench` with GHC 8.10.1-rc1, it will fail with the following error:

```
[4 of 5] Compiling SOPBench.Type    ( bench/SOPBench/Type.hs, /home/rgscott/Documents/Hacking/Haskell/cabal-sandbox/generics-sop/dist-newstyle/build/x86_64-linux/ghc-8.10.0.20200123/generics-sop-0.5.0.0/b/generics-sop-bench/build/generics-sop-bench/generics-sop-bench-tmp/SOPBench/Type.o, /home/rgscott/Documents/Hacking/Haskell/cabal-sandbox/generics-sop/dist-newstyle/build/x86_64-linux/ghc-8.10.0.20200123/generics-sop-0.5.0.0/b/generics-sop-bench/build/generics-sop-bench/generics-sop-bench-tmp/SOPBench/Type.dyn_o )

bench/SOPBench/Type.hs:197:15: error:
    • No instance for (SOP.Generic (S20 'SOPTH))
        arising from a use of ‘soproundtrip’
    • In the expression: soproundtrip
      In an equation for ‘roundtrip’: roundtrip = soproundtrip
      In the instance declaration for ‘Roundtrip (S20 'SOPTH)’
    |
197 |   roundtrip = soproundtrip
    |               ^^^^^^^^^^^^
```

This is due to changes introduces in GHC's constraint solver in 8.10 that cause it to solve constraints in top-level groups sooner. (See [this section](https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.10?version_id=1da3660a#the-order-of-th-splices-is-more-important) of the GHC 8.10 Migration Guide for more details.)

Patch incoming.
