### PR TITLE
Make the benchmarks compile on GHC 8.10.1

### LINKED ISSUE #117: Benchmarks fail to build on GHC 8.10.1
If you attempt to compile `generics-sop-bench` with GHC 8.10.1-rc1, it will fail with the following error:

```
[4 of 5] Compiling SOPBench.Type    ( bench/SOPBench/Type.hs, /home/rgscott/Documents/Hacking/Haskell/cabal-sandbox/generics-sop/dist-newstyle/build/x86_64-linux/ghc-8.10.0.20200123/generics-sop-0.5.0.0/b/generics-sop-bench/build/generics-sop-bench/generics-sop-bench-tmp/SOPBench/Type.o, /home/rgscott/Documents/Hacking/Haskell/cabal-sandbox/generics-sop/dist-newstyle/build/x86_64-linux/ghc-8.10.0.20200123/generics-sop-0.5.0.0/b/generics-sop-bench/build/generics-sop-bench/generics-sop-bench-tmp/SOPBench/Type.dyn_o )

bench/SOPBench/Type.hs:197:15: error:
    • No instance for (SOP.Generic (S20 'SOPTH))
        arising from a use of ‘soproundtrip’
    • In the expression: soproundtrip
      In an equation for ‘roundtrip’: roundtrip = soproundtrip
      In the instance declaration for ‘Roundtrip (S20 'SOPTH)’
    |
197 |   roundtrip = soproundtrip
    |               ^^^^^^^^^^^^
```

This is due to changes introduces in GHC's constraint solver in 8.10 that cause it to solve constraints in top-level groups sooner. (See [this section](https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.10?version_id=1da3660a#the-order-of-th-splices-is-more-important) of the GHC 8.10 Migration Guide for more details.)

Patch incoming.

### PR DESCRIPTION
**Pull request by RyanGlScott**
This reorders some TH splices to make them friendlier to GHC 8.10.1's constraint solver. Fixes #117.

### CODE REVIEW

**Comment by kosmikus** [comment]
Thanks. This is looking good, except that I think CI still disables building benchmarks for ghc 8.8 and up, which includes 8.10. I'm currently not sure why we disabled them for 8.8, but if the purpose is to make them work in 8.10, we should enable them there.

**Comment by RyanGlScott** [comment]
Oops, I overlooked that sneaky `"--benchmarks-jobs=<8.8"` bit lurking `.travis.yml`. I've pushed an update to remove it.

**Comment by kosmikus** [comment]
Restarted one CI job because of what I believe to be a transient failure.

**Comment by phadej** [comment]
CI turned green, merging
